apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: myapp
  labels:
    app: mynginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: mynginx
          image: niftyshorts/custom-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # comment out the below securityContext if you want the checkov build to fail!
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  runAsNonRoot: true
          #  runAsUser: 101
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
  namespace: myapp
spec:
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
